version: '3.8'

services:
  db:
    image: postgres:14 
    container_name: postgres_db2
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend:
    build: .
    container_name: backend_app
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase?schema=public
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend_network
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
